"""
games/quiz_data.py — 60 questions (20 par match)
Structure : { "q": question, "choices": [A,B,C,D], "answer": index }
"""

ALL_QUESTIONS = [
    # ── MATCH 1 — Demi-finale A vs B (Q1–20) ─────────────────────────────────
    {"q": "Quelle est la capitale du Maroc ?",
     "choices": ["Casablanca","Rabat","Fès","Marrakech"], "answer": 1},
    {"q": "Combien de planètes composent notre système solaire ?",
     "choices": ["7","8","9","10"], "answer": 1},
    {"q": "Qui a peint la Joconde ?",
     "choices": ["Michel-Ange","Picasso","Léonard de Vinci","Raphaël"], "answer": 2},
    {"q": "Quelle est la plus grande planète du système solaire ?",
     "choices": ["Saturne","Uranus","Jupiter","Neptune"], "answer": 2},
    {"q": "Quelle est la capitale de la France ?",
     "choices": ["Lyon","Marseille","Paris","Bordeaux"], "answer": 2},
    {"q": "Quel est le symbole chimique de l'or ?",
     "choices": ["Ag","Fe","Cu","Au"], "answer": 3},
    {"q": "En quelle année le Maroc a-t-il obtenu son indépendance ?",
     "choices": ["1944","1952","1956","1960"], "answer": 2},
    {"q": "Quelle est la langue officielle du Brésil ?",
     "choices": ["Espagnol","Anglais","Portugais","Français"], "answer": 2},
    {"q": "Quel est le plus grand océan du monde ?",
     "choices": ["Atlantique","Indien","Arctique","Pacifique"], "answer": 3},
    {"q": "Qui a découvert la gravitation universelle ?",
     "choices": ["Einstein","Galilée","Newton","Archimède"], "answer": 2},
    {"q": "Combien de côtés a un hexagone ?",
     "choices": ["5","6","7","8"], "answer": 1},
    {"q": "Quelle est la capitale de l'Espagne ?",
     "choices": ["Barcelone","Séville","Valence","Madrid"], "answer": 3},
    {"q": "Quel est le plus long fleuve d'Afrique ?",
     "choices": ["Congo","Zambèze","Niger","Nil"], "answer": 3},
    {"q": "Combien font 12 × 12 ?",
     "choices": ["132","144","124","148"], "answer": 1},
    {"q": "Quel animal est le plus grand du monde ?",
     "choices": ["Éléphant d'Afrique","Requin baleine","Girafe","Baleine bleue"], "answer": 3},
    {"q": "Dans quel pays se trouve le mont Fuji ?",
     "choices": ["Chine","Corée","Japon","Vietnam"], "answer": 2},
    {"q": "Qui a écrit 'Les Misérables' ?",
     "choices": ["Balzac","Zola","Flaubert","Victor Hugo"], "answer": 3},
    {"q": "Quelle est la formule de l'eau ?",
     "choices": ["CO2","H2O","O2","HCl"], "answer": 1},
    {"q": "Quel est le continent le plus grand ?",
     "choices": ["Amériques","Afrique","Asie","Europe"], "answer": 2},
    {"q": "Combien de couleurs y a-t-il dans un arc-en-ciel ?",
     "choices": ["5","6","7","8"], "answer": 2},

    # ── MATCH 2 — Demi-finale C vs D (Q21–40) ────────────────────────────────
    {"q": "Quelle est la capitale de l'Italie ?",
     "choices": ["Milan","Naples","Florence","Rome"], "answer": 3},
    {"q": "Qui a inventé le téléphone ?",
     "choices": ["Edison","Tesla","Bell","Marconi"], "answer": 2},
    {"q": "Quel est le pays le plus peuplé du monde ?",
     "choices": ["Inde","États-Unis","Chine","Indonésie"], "answer": 2},
    {"q": "Quelle est la capitale de l'Allemagne ?",
     "choices": ["Munich","Hambourg","Berlin","Francfort"], "answer": 2},
    {"q": "Combien d'os y a-t-il dans le corps humain adulte ?",
     "choices": ["186","206","226","246"], "answer": 1},
    {"q": "Quel est le plus haut sommet du monde ?",
     "choices": ["K2","Kangchenjunga","Mont Blanc","Everest"], "answer": 3},
    {"q": "En quelle année a eu lieu la Révolution française ?",
     "choices": ["1776","1789","1804","1815"], "answer": 1},
    {"q": "Quel est l'élément le plus abondant dans l'univers ?",
     "choices": ["Oxygène","Hélium","Carbone","Hydrogène"], "answer": 3},
    {"q": "Quelle est la capitale du Japon ?",
     "choices": ["Osaka","Kyoto","Hiroshima","Tokyo"], "answer": 3},
    {"q": "Combien de grammes dans un kilogramme ?",
     "choices": ["10","100","1 000","10 000"], "answer": 2},
    {"q": "Qui était le premier président des États-Unis ?",
     "choices": ["Jefferson","Lincoln","Adams","Washington"], "answer": 3},
    {"q": "Quel est le pays d'origine du football ?",
     "choices": ["France","Espagne","Brésil","Angleterre"], "answer": 3},
    {"q": "Combien de notes y a-t-il dans une octave musicale ?",
     "choices": ["5","7","8","12"], "answer": 2},
    {"q": "Quelle est la capitale de l'Australie ?",
     "choices": ["Sydney","Melbourne","Brisbane","Canberra"], "answer": 3},
    {"q": "Quel organe filtre le sang dans le corps humain ?",
     "choices": ["Foie","Poumon","Cœur","Rein"], "answer": 3},
    {"q": "Combien de secondes dans une heure ?",
     "choices": ["360","600","3 600","36 000"], "answer": 2},
    {"q": "Qui a composé la Symphonie nº 5 ?",
     "choices": ["Mozart","Bach","Chopin","Beethoven"], "answer": 3},
    {"q": "Quel est le métal le plus léger ?",
     "choices": ["Fer","Cuivre","Lithium","Aluminium"], "answer": 2},
    {"q": "Quelle est la capitale du Canada ?",
     "choices": ["Toronto","Montréal","Vancouver","Ottawa"], "answer": 3},
    {"q": "En quelle année Neil Armstrong a-t-il marché sur la Lune ?",
     "choices": ["1965","1967","1969","1971"], "answer": 2},

    # ── MATCH 3 — Finale (Q41–60) ─────────────────────────────────────────────
    {"q": "Quelle est la vitesse de la lumière (km/s) ?",
     "choices": ["150 000","200 000","300 000","500 000"], "answer": 2},
    {"q": "Quel est le plus grand pays du monde par superficie ?",
     "choices": ["Canada","Chine","États-Unis","Russie"], "answer": 3},
    {"q": "Quel gaz les plantes absorbent-elles pour la photosynthèse ?",
     "choices": ["Oxygène","Azote","CO2","Vapeur d'eau"], "answer": 2},
    {"q": "En quelle année a été fondée l'ONU ?",
     "choices": ["1939","1945","1950","1955"], "answer": 1},
    {"q": "Quelle est la monnaie du Japon ?",
     "choices": ["Won","Yuan","Yen","Dong"], "answer": 2},
    {"q": "Combien de dents permanentes a un adulte ?",
     "choices": ["28","30","32","34"], "answer": 2},
    {"q": "Quel est le symbole chimique du fer ?",
     "choices": ["Fr","Fn","Fe","Fa"], "answer": 2},
    {"q": "Qui a écrit 'Don Quichotte' ?",
     "choices": ["Shakespeare","Dante","Cervantes","Molière"], "answer": 2},
    {"q": "Combien de joueurs dans une équipe de football ?",
     "choices": ["9","10","11","12"], "answer": 2},
    {"q": "Quelle planète est surnommée 'la planète rouge' ?",
     "choices": ["Vénus","Jupiter","Mercure","Mars"], "answer": 3},
    {"q": "Quelle est la capitale de la Chine ?",
     "choices": ["Shanghai","Hong Kong","Nankin","Pékin"], "answer": 3},
    {"q": "Quel est l'os le plus long du corps humain ?",
     "choices": ["Tibia","Humérus","Fémur","Radius"], "answer": 2},
    {"q": "En quelle année a été construit le mur de Berlin ?",
     "choices": ["1955","1958","1961","1965"], "answer": 2},
    {"q": "Quel est le plus petit pays du monde ?",
     "choices": ["Monaco","Saint-Marin","Liechtenstein","Vatican"], "answer": 3},
    {"q": "Combien de continents y a-t-il sur Terre ?",
     "choices": ["5","6","7","8"], "answer": 2},
    {"q": "Quelle est la capitale du Brésil ?",
     "choices": ["Rio de Janeiro","São Paulo","Salvador","Brasilia"], "answer": 3},
    {"q": "Quel est le numéro atomique de l'hydrogène ?",
     "choices": ["1","2","3","4"], "answer": 0},
    {"q": "Qui a peint la chapelle Sixtine ?",
     "choices": ["Raphaël","Léonard de Vinci","Michel-Ange","Botticelli"], "answer": 2},
    {"q": "Combien font 2⁸ (deux puissance huit) ?",
     "choices": ["128","256","512","1024"], "answer": 1},
    {"q": "Quelle est la capitale de l'Égypte ?",
     "choices": ["Alexandrie","Louxor","Assouan","Le Caire"], "answer": 3},
]
